media-user-token: "AuTo/8Tpmz25is2EOVD7fO1cXqhNq0866hM28k9P8BHkFHw5S0dB4/INbJO09Q09FP71eYY/U/OSpFyxY1DELg+f9EZjs5yMbytWXRbg+zfoGPVZXATpRFYBWLgIJMMFdxgjrZZnvbgI/5vn3Q37n/PGl5GjSaRHXG4Ap9FpiNTJKUJ7VgTP6mcVX3sG4ms9xgAYNb9u+RcVh5PRhlAozin8keO3ijWhw5nA/kFct90mdYe9QQ==" #If you need to obtain the lyrics, need to change it
authorization-token: "your-authorization-token" #You don't need to change it; it can automatically obtain token
language: ""         #supportedLanguage by each storefront --> https://gist.github.com/itouakirai/c8ba9df9dc65bd300094103b058731d0
lrc-type: "lyrics"   #lyrics or syllable-lyrics
lrc-format: "lrc"   #lrc or ttml
embed-lrc: true     #Unable to embed ttml lyrics
save-lrc-file: false
save-artist-cover: false
save-animated-artwork: false    # If enabled, requires ffmpeg
emby-animated-artwork: false    # If enabled, requires ffmpeg
embed-cover: true
cover-size: 3000x3000
cover-format: jpg       #jpg png or original
alac-save-folder: /storage/emulated/0/Music/Music Rippers/AM downloads/AM-DL downloads
atmos-save-folder: /storage/emulated/0/Music/Music Rippers/AM downloads/AM-DL-Atmos downloads
check: "http://drm.zhaarey.cn:19919/m3u8" # API or .txt
force-api: false
decrypt-m3u8-port: "127.0.0.1:10020"
get-m3u8-port: "127.0.0.1:20020"
get-m3u8-from-device: true
#set 'all' to retrieve all m3u8, and set 'hires' to only detect hires m3u8.
get-m3u8-mode: hires # all hires
alac-max: 192000  #192000 96000 48000 44100
atmos-max: 2768  #2768 2448
limit-max: 200
#{AlbumId} {AlbumName} {ArtistName} {ReleaseDate} {ReleaseYear} {UPC} {Copyright} {Quality} {Codec} {Tag} {RecordLabel}
#example: {ReleaseYear} - {ArtistName} - {AlbumName}({AlbumId})({UPC})({Copyright}){Codec}
album-folder-format: "{AlbumName}"
#{PlaylistId} {PlaylistName} {ArtistName} {Quality} {Codec} {Tag}
playlist-folder-format: "{PlaylistName}"
#{SongId} {SongNumer} {SongName} {DiscNumber} {TrackNumber} {Quality} {Codec} {Tag}
#example: Disk {DiscNumber} - Track {TrackNumber} {SongName} [{Quality}]{{Tag}}"
song-file-format: "{SongNumer}. {SongName}"
#{ArtistId} {ArtistName}/{UrlArtistName}
#if artist-folder-format set "",will not make artist folder
artist-folder-format: "{ArtistName}"
#if set "" will not add tag
explicit-choice : "[E]"
clean-choice : "[C]"
apple-master-choice : "[M]"
#if set true,for playlst,will use songinfo for meta #albumname track disk
use-songinfo-for-playlist: true
#if set true,will download album cover for playlist
dl-albumcover-for-playlist: true
